name: 'Migrate database schema'

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-20.04
    env:
      REDSHIFT_HOST: bettzeit-dw-instance.cmmw5dhxikj7.eu-central-1.redshift.amazonaws.com
      REDSHIFT_PORT: 5439
      REDSHIFT_USER: gundu_rao
      REDSHIFT_DB: bettzeit
      REDSHIFT_PASS: PgWs8Wvv6D
    steps:
      - uses: actions/checkout@v2
      - run: > 
           docker build . -t flyway_image 
           -f ${{ github.workspace }}/Dockerfile
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/sql:/flyway/sql:ro
          flyway_image
          -url="jdbc:redshift://${{ env.REDSHIFT_HOST }}:${{ env.REDSHIFT_PORT }}/${{ env.REDSHIFT_DB }}?sslmode=require"
          -user="${{ env.REDSHIFT_USER }}"
          -password="${{ env.REDSHIFT_PASS }}"
          -jarDirs=/flyway/drivers
          migrate
